### PR TITLE
Allow joining lines when meaningful.

### PR DESCRIPTION
**Pull request by aartaka**
Hi! 

This PR allows joining paragraph/quote lines when they are grouped together (between blank lines). This is meaningful because, although Gemtext is intended for "long lines", some people (like me) still try to fill it to 80 columns. This is widespread enough for e.g. Skribilo to provide line joining and Lagrange to do line grouping.

Looks good to you?

### CODE REVIEW

**Comment by omar-polo** [comment]
Hello @aartaka, thanks for the patch!  The diff looks fine to me, but I'm unsure about the underlying idea.  I've seen a few pages where the gemtext is folded at 80 columns (or so), but it's something that is against the "spirit" of gemtext, since every "bare" line is a standalone paragraph, and the instances of pages with manually folded text are a very small minority in my experience.

On the other hand, I doubt that this is going to break anything.  Almost everyone will leave an empty line between "paragraphs", so it should just work in practice.  I am surprised to learn that lagrange does this by default.

I'll have to think about it a bit more (and to ponder whether this makes sense for my other [gemini client](https://github.com/omar-polo/telescope) :P)

**Comment by aartaka** [comment]
>Hello @aartaka, thanks for the patch!  The diff looks fine to me, but I'm unsure about the underlying idea.  I've seen a few pages where the gemtext is folded at 80 columns (or so), but it's something that is against the "spirit" of gemtext, since every "bare" line is a standalone paragraph, and the instances of pages with manually folded text are a very small minority in my experience.

That's partly why I'm hiding that behind a boolean flag—it's an opinionated change that will mostly be useful for document autoring for those (like me) who split lines and use blank ones as "paragraph" separators.

There's spirit of Gemini, but there also is actual practice. So this patch enables both, but doesn't force either.

>On the other hand, I doubt that this is going to break anything.  Almost everyone will leave an empty line between "paragraphs", so it should just work in practice.  I am surprised to learn that lagrange does this by default.

To be precise, lagrange still splits things into paragraphs, but the padding is so small they do look like one block of text

>I'll have to think about it a bit more

No rush!

**Comment by omar-polo** [comment]
Sorry for the delay.

> That's partly why I'm hiding that behind a boolean flag—it's an opinionated change that will mostly be useful for document autoring for those (like me) who split lines and use blank ones as "paragraph" separators.
> 
> There's spirit of Gemini, but there also is actual practice. So this patch enables both, but doesn't force either.

Yes, I agree.  Regardless of the spirit of the protocol, in practice we should give the user enough liberty to do what they please.  This is not adding much complexity to the library, so I'm fine with it.

> To be precise, lagrange still splits things into paragraphs, but the padding is so small they do look like one block of text

Ah, I see!


I have merged your PR and then on top added the `join-lines` parameter to `gemtext:parse-string` too and added a simple test case for it.

**Comment by omar-polo** [comment]
Oops, forgot to thank you for the diff!  Thanks! :)

**Comment by aartaka** [comment]
Thank you for maintaining the library :heart:

**Pull request merged**
